# -*- coding: utf-8 -*-
"""BONUS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dpNp6s46K2xo2yeoqVwEFcWlfHa86g0U
"""

import numpy as np
import matplotlib.pyplot as plt

N = 500
x = np.linspace(-5, 5, N)
dx = x[1] - x[0]

k = 10
V = 0.5 * k * x**2

main_diag = (1 / dx**2) + V

off_diag = (-1 / (2 * dx**2)) * np.ones(N - 1)

H = (
    np.diag(main_diag)
    + np.diag(off_diag, k=1)
    + np.diag(off_diag, k=-1)
)

energies, wavefunctions = np.linalg.eigh(H)

for n in range(wavefunctions.shape[1]):
  norm = np.sqrt(np.sum(np.abs(wavefunctions[:, n])**2) * dx)
  wavefunctions[:, n] = wavefunctions[:, n] / norm

plt.figure(figsize=(10, 6))
plt.plot(x, V, label="Potential V(x)", color="black")
alpha = 2.0

for n in range(3):
    En = energies[n]
    psi_n = wavefunctions[:, n]
    plt.axhline(En, linestyle="--", alpha=0.6)
    plt.plot(x,En + alpha * psi_n,label=f"psi{n}(x), E{n} = {En:.4f}")
plt.xlabel("Position x")
plt.ylabel("Energy / shifted wavefunction")
plt.title("Quantum Harmonic Oscillator using Finite Difference Method")
plt.legend()
plt.grid(True)
plt.ylim(0, energies[2] + 8)

plt.show()

print("Lowest three energy levels:")
for n in range(3):
    print(f"E{n} = {energies[n]:.6f}")

