# -*- coding: utf-8 -*-
"""gram_schmidt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126aBc6-Bwpy_8sCn4z56NvxPCYi5J20q
"""

import numpy as np
#function
def gram_schmidt(A):
  cols=A.shape[1]
  Q=np.zeros(A.shape)
  for i in range(cols):
    v=A[:,i]
    for j in range(i):
      q=np.dot(v,Q[:,j])*Q[:,j]
      v=v-q
    v=v/(np.linalg.norm(v))
    Q[:,i]=v
  return Q
#test case
A=np.array([[1,1,0],[0,1,0],[0,1,1]])
Q=gram_schmidt(A)
print(Q)
#verification
print(Q.T @ Q)
print(np.allclose(Q.T @ Q, np.eye(A.shape[1])))