# -*- coding: utf-8 -*-
"""TISE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNfLcIVMZ93XwyQxJIM0kLFfuAT3uH85
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 5, 500)

def simulate_wavefunction(x, E, V):
    if E > V:
        k = np.sqrt(2 * (E - V))
        psi = np.cos(k * x)

    elif E < V:
        k1 = np.sqrt(2 * (V - E))
        psi = np.exp(-k1 * x)

    else:
        psi = np.ones_like(x)

    return psi

psi_A = simulate_wavefunction(x, E=12, V=2)
psi_B = simulate_wavefunction(x, E=2, V=7)
psi_C = simulate_wavefunction(x, E=5, V=5)

plt.figure(figsize=(10, 6))

plt.plot(x, psi_A, label="Case A: E=12, V=2 Oscillatory", linestyle="-")
plt.plot(x, psi_B, label="Case B: E=2, V=7 Decaying", linestyle="--")
plt.plot(x, psi_C, label="Case C: E=5, V=5 Threshold", linestyle=":")

plt.xlabel("Position x")
plt.ylabel("Wavefunction psi(x)")
plt.title("1D TISE: Wavefunction Stimulations")
plt.legend()
plt.grid(True)

plt.show()